### PR TITLE
refactor(deps): replaced external `pkg/errors` with built-in `errors` package

### PR DESCRIPTION
**Pull request by asalvi0**
## Description

This PR removes the dependency with the external package `errors`, using the standard package introduced in `1.20`.

## Benchmarking

Frisbee tries to adhere to strict performance requirements, so please make sure to run `go test -bench=. ./...` and paste the results below:

### Benchmarking Results:

With pull request changes

```shell
goos: darwin
goarch: arm64
pkg: github.com/loopholelabs/frisbee-go
BenchmarkAsyncThroughputPipe/32_Bytes-10                   32296             35411 ns/op          90.37 MB/s       10360 B/op        213 allocs/op
BenchmarkAsyncThroughputPipe/512_Bytes-10                  30027             39819 ns/op        1285.82 MB/s       10341 B/op        212 allocs/op
BenchmarkAsyncThroughputPipe/1024_Bytes-10                 27834             41675 ns/op        2457.11 MB/s       10368 B/op        212 allocs/op
BenchmarkAsyncThroughputPipe/2048_Bytes-10                 24768             48115 ns/op        4256.46 MB/s       10499 B/op        215 allocs/op
BenchmarkAsyncThroughputPipe/4096_Bytes-10                 18666             66653 ns/op        6145.23 MB/s       10807 B/op        220 allocs/op
BenchmarkAsyncThroughputNetwork/32_Bytes-10                29962             40470 ns/op          79.07 MB/s         260 B/op          4 allocs/op
BenchmarkAsyncThroughputNetwork/512_Bytes-10               25942             45905 ns/op        1115.35 MB/s         258 B/op          4 allocs/op
BenchmarkAsyncThroughputNetwork/1024_Bytes-10              22006             55842 ns/op        1833.76 MB/s         260 B/op          4 allocs/op
BenchmarkAsyncThroughputNetwork/2048_Bytes-10              16287             76190 ns/op        2688.01 MB/s         262 B/op          4 allocs/op
BenchmarkAsyncThroughputNetwork/4096_Bytes-10              10000            114330 ns/op        3582.61 MB/s         279 B/op          4 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/1_Pair,_32_Bytes-10                25851             41482 ns/op          77.14 MB/s         354 B/op          4 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/2_Pair,_32_Bytes-10                27790             43930 ns/op          72.84 MB/s         701 B/op          8 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/5_Pair,_32_Bytes-10                18759             54336 ns/op          58.89 MB/s        1957 B/op         20 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/10_Pair,_32_Bytes-10               10302            117023 ns/op          27.35 MB/s        4968 B/op         40 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/Half_CPU_Pair,_32_Bytes-10         19234             59413 ns/op          53.86 MB/s        1937 B/op         20 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/CPU_Pair,_32_Bytes-10               9847            127542 ns/op          25.09 MB/s        5059 B/op         40 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/Double_CPU_Pair,_32_Bytes-10                5826            203131 ns/op          15.75 MB/s       13440 B/op         81 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/1_Pair,_512_Bytes-10                       23793             51680 ns/op         990.71 MB/s         362 B/op          4 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/2_Pair,_512_Bytes-10                       23035             53182 ns/op         962.73 MB/s         738 B/op          8 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/5_Pair,_512_Bytes-10                       16392             69995 ns/op         731.48 MB/s        2052 B/op         20 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/10_Pair,_512_Bytes-10                       8164            144231 ns/op         354.98 MB/s        5556 B/op         40 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/Half_CPU_Pair,_512_Bytes-10                17181             76331 ns/op         670.76 MB/s        2015 B/op         20 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/CPU_Pair,_512_Bytes-10                      6481            155015 ns/op         330.29 MB/s        6321 B/op         40 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/Double_CPU_Pair,_512_Bytes-10               3901            261146 ns/op         196.06 MB/s       17529 B/op         81 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/1_Pair,_4096_Bytes-10                      12154            100009 ns/op        4095.62 MB/s         485 B/op          4 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/2_Pair,_4096_Bytes-10                       8266            122435 ns/op        3345.45 MB/s        1229 B/op          8 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/5_Pair,_4096_Bytes-10                       2565            417310 ns/op         981.52 MB/s        6732 B/op         21 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/10_Pair,_4096_Bytes-10                      1478            796144 ns/op         514.48 MB/s       20499 B/op         42 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/Half_CPU_Pair,_4096_Bytes-10                2966            397153 ns/op        1031.34 MB/s        6008 B/op         21 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/CPU_Pair,_4096_Bytes-10                     1513            781571 ns/op         524.07 MB/s       20285 B/op         43 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/Double_CPU_Pair,_4096_Bytes-10               748           1548332 ns/op         264.54 MB/s       73785 B/op         88 allocs/op
BenchmarkThroughputClient/test-10                                                     62          18157163 ns/op        1847.97 MB/s       35894 B/op        137 allocs/op
BenchmarkThroughputResponseClient/test-10                                             63          18861196 ns/op        1778.99 MB/s       15585 B/op         39 allocs/op
BenchmarkThroughputServerSingle/test-10                                               58          18984443 ns/op        1767.44 MB/s       31579 B/op        107 allocs/op
BenchmarkThroughputServerUnlimited/test-10                                            30          46219551 ns/op         725.97 MB/s     9887190 B/op     144109 allocs/op
BenchmarkThroughputServerLimited/test-10                                              46         198135423 ns/op         169.35 MB/s     7625711 B/op     134033 allocs/op
BenchmarkThroughputResponseServerSingle/test-10                                       66          17931438 ns/op        1871.23 MB/s       21260 B/op         75 allocs/op
BenchmarkThroughputResponseServerSlowSingle/test-10                                    1        5584337958 ns/op           6.01 MB/s    37874792 B/op     261220 allocs/op
BenchmarkThroughputResponseServerSlowUnlimited/test-10                                30          41717171 ns/op         804.32 MB/s     7260833 B/op     131304 allocs/op
BenchmarkThroughputResponseServerSlowLimited/test-10                                  15          76982758 ns/op         435.86 MB/s     7277396 B/op     131894 allocs/op
BenchmarkSyncThroughputPipe/32_Bytes-10                                             8880            133809 ns/op          23.91 MB/s        1856 B/op        204 allocs/op
BenchmarkSyncThroughputPipe/512_Bytes-10                                            8942            134983 ns/op         379.31 MB/s        1856 B/op        204 allocs/op
BenchmarkSyncThroughputPipe/1024_Bytes-10                                           9012            134175 ns/op         763.18 MB/s        1856 B/op        204 allocs/op
BenchmarkSyncThroughputPipe/2048_Bytes-10                                           8688            134200 ns/op        1526.08 MB/s        1856 B/op        204 allocs/op
BenchmarkSyncThroughputPipe/4096_Bytes-10                                           8322            138994 ns/op        2946.90 MB/s        1857 B/op        204 allocs/op
BenchmarkSyncThroughputNetwork/32_Bytes-10                                          2121            566724 ns/op           5.65 MB/s        1857 B/op        204 allocs/op
BenchmarkSyncThroughputNetwork/512_Bytes-10                                         2079            577115 ns/op          88.72 MB/s        1856 B/op        204 allocs/op
BenchmarkSyncThroughputNetwork/1024_Bytes-10                                        1933            567786 ns/op         180.35 MB/s        1863 B/op        204 allocs/op
BenchmarkSyncThroughputNetwork/2048_Bytes-10                                        2143            614143 ns/op         333.47 MB/s        1861 B/op        204 allocs/op
BenchmarkSyncThroughputNetwork/4096_Bytes-10                                        2194            556028 ns/op         736.65 MB/s        1862 B/op        204 allocs/op
BenchmarkAsyncThroughputLarge/1MB-10                                                 112          11607042 ns/op        9033.96 MB/s       68559 B/op          4 allocs/op
BenchmarkAsyncThroughputLarge/2MB-10                                                  62          20254522 ns/op        10353.99 MB/s      80673 B/op          4 allocs/op
BenchmarkAsyncThroughputLarge/4MB-10                                                  16          67193414 ns/op        6242.14 MB/s      808599 B/op          6 allocs/op
BenchmarkAsyncThroughputLarge/8MB-10                                                   7         143540060 ns/op        5844.09 MB/s     2414365 B/op          9 allocs/op
BenchmarkAsyncThroughputLarge/16MB-10                                                  4         314361333 ns/op        5336.92 MB/s    14325822 B/op         14 allocs/op
BenchmarkSyncThroughputLarge/1MB-10                                                   80          15022942 ns/op        6979.83 MB/s        1865 B/op        204 allocs/op
BenchmarkSyncThroughputLarge/2MB-10                                                   40          27666856 ns/op        7580.02 MB/s      531404 B/op        205 allocs/op
BenchmarkSyncThroughputLarge/4MB-10                                                   15          69505194 ns/op        6034.52 MB/s     4223799 B/op        211 allocs/op
BenchmarkSyncThroughputLarge/8MB-10                                                    7         148533440 ns/op        5647.62 MB/s    11917477 B/op        216 allocs/op
BenchmarkSyncThroughputLarge/16MB-10                                                   4         295611948 ns/op        5675.42 MB/s        2036 B/op        206 allocs/op
BenchmarkTCPThroughput/32_Bytes-10                                                 21064             55911 ns/op          57.23 MB/s         304 B/op          4 allocs/op
BenchmarkTCPThroughput/512_Bytes-10                                                12085             99954 ns/op         512.24 MB/s         304 B/op          4 allocs/op
BenchmarkTCPThroughput/1024_Bytes-10                                                7849            153155 ns/op         668.60 MB/s         304 B/op          4 allocs/op
BenchmarkTCPThroughput/2048_Bytes-10                                                4476            262357 ns/op         780.61 MB/s         304 B/op          4 allocs/op
BenchmarkTCPThroughput/4096_Bytes-10                                                2401            495055 ns/op         827.38 MB/s         304 B/op          4 allocs/op
BenchmarkTCPThroughput/1MB-10                                                         81          14637847 ns/op        7163.46 MB/s         304 B/op          4 allocs/op
BenchmarkTCPThroughput/2MB-10                                                         36          29643941 ns/op        7074.47 MB/s         304 B/op          4 allocs/op
BenchmarkTCPThroughput/4MB-10                                                         19          62863757 ns/op        6672.05 MB/s         304 B/op          4 allocs/op
BenchmarkTCPThroughput/8MB-10                                                          9         135989444 ns/op        6168.57 MB/s         304 B/op          4 allocs/op
BenchmarkTCPThroughput/16MB-10                                                         4         288876854 ns/op        5807.74 MB/s         304 B/op          4 allocs/op
PASS
ok      github.com/loopholelabs/frisbee-go      153.883s
?       github.com/loopholelabs/frisbee-go/internal/dialer      [no test files]
goos: darwin
goarch: arm64
pkg: github.com/loopholelabs/frisbee-go/pkg/metadata
BenchmarkEncode-10              100413451               11.70 ns/op
BenchmarkDecode-10              341418104                3.503 ns/op
BenchmarkEncodeDecode-10        77518543                15.14 ns/op
PASS
ok      github.com/loopholelabs/frisbee-go/pkg/metadata 4.702s
PASS
ok      github.com/loopholelabs/frisbee-go/pkg/packet   0.094s
```

From original source

```shell
goos: darwin
goarch: arm64
pkg: github.com/loopholelabs/frisbee-go
BenchmarkAsyncThroughputPipe/32_Bytes-10                   25902             45008 ns/op          71.10 MB/s       10276 B/op        211 allocs/op
BenchmarkAsyncThroughputPipe/512_Bytes-10                  23438             45079 ns/op        1135.79 MB/s       10320 B/op        212 allocs/op
BenchmarkAsyncThroughputPipe/1024_Bytes-10                 25460             48947 ns/op        2092.05 MB/s       10353 B/op        212 allocs/op
BenchmarkAsyncThroughputPipe/2048_Bytes-10                 19048             61957 ns/op        3305.52 MB/s       10509 B/op        215 allocs/op
BenchmarkAsyncThroughputPipe/4096_Bytes-10                 14710             70261 ns/op        5829.73 MB/s       10884 B/op        220 allocs/op
BenchmarkAsyncThroughputNetwork/32_Bytes-10                28687             40220 ns/op          79.56 MB/s         259 B/op          4 allocs/op
BenchmarkAsyncThroughputNetwork/512_Bytes-10               25822             49279 ns/op        1038.98 MB/s         260 B/op          4 allocs/op
BenchmarkAsyncThroughputNetwork/1024_Bytes-10              21032             61602 ns/op        1662.30 MB/s         260 B/op          4 allocs/op
BenchmarkAsyncThroughputNetwork/2048_Bytes-10              16626             67109 ns/op        3051.73 MB/s         262 B/op          4 allocs/op
BenchmarkAsyncThroughputNetwork/4096_Bytes-10              12656             94288 ns/op        4344.12 MB/s         260 B/op          4 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/1_Pair,_32_Bytes-10                30640             43202 ns/op          74.07 MB/s         337 B/op          4 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/2_Pair,_32_Bytes-10                25413             43248 ns/op          73.99 MB/s         717 B/op          8 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/5_Pair,_32_Bytes-10                18369             63275 ns/op          50.57 MB/s        1970 B/op         20 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/10_Pair,_32_Bytes-10                8268            121978 ns/op          26.23 MB/s        5553 B/op         40 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/Half_CPU_Pair,_32_Bytes-10         23400             55341 ns/op          57.82 MB/s        1827 B/op         20 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/CPU_Pair,_32_Bytes-10              10218            125997 ns/op          25.40 MB/s        4997 B/op         40 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/Double_CPU_Pair,_32_Bytes-10                5842            214603 ns/op          14.91 MB/s       13529 B/op         81 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/1_Pair,_512_Bytes-10                       25608             46824 ns/op        1093.47 MB/s         353 B/op          4 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/2_Pair,_512_Bytes-10                       21571             51277 ns/op         998.49 MB/s         752 B/op          8 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/5_Pair,_512_Bytes-10                       17416             68111 ns/op         751.71 MB/s        2005 B/op         20 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/10_Pair,_512_Bytes-10                       8305            142072 ns/op         360.38 MB/s        5520 B/op         40 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/Half_CPU_Pair,_512_Bytes-10                15864             71327 ns/op         717.82 MB/s        2076 B/op         20 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/CPU_Pair,_512_Bytes-10                      6490            158051 ns/op         323.95 MB/s        6352 B/op         40 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/Double_CPU_Pair,_512_Bytes-10               4644            251786 ns/op         203.35 MB/s       15625 B/op         81 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/1_Pair,_4096_Bytes-10                      12555             92833 ns/op        4412.21 MB/s         498 B/op          4 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/2_Pair,_4096_Bytes-10                      11335            105739 ns/op        3873.70 MB/s        1035 B/op          8 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/5_Pair,_4096_Bytes-10                       2868            398413 ns/op        1028.08 MB/s        6193 B/op         21 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/10_Pair,_4096_Bytes-10                      1503            793355 ns/op         516.29 MB/s       20789 B/op         43 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/Half_CPU_Pair,_4096_Bytes-10                2810            406955 ns/op        1006.50 MB/s        6228 B/op         20 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/CPU_Pair,_4096_Bytes-10                     1527            790481 ns/op         518.17 MB/s       20107 B/op         43 allocs/op
BenchmarkAsyncThroughputNetworkMultiple/Double_CPU_Pair,_4096_Bytes-10               764           1567374 ns/op         261.33 MB/s       74171 B/op         90 allocs/op
BenchmarkThroughputClient/test-10                                                     62          18594312 ns/op        1804.53 MB/s       40305 B/op        176 allocs/op
BenchmarkThroughputResponseClient/test-10                                             63          18474802 ns/op        1816.20 MB/s       18222 B/op         46 allocs/op
BenchmarkThroughputServerSingle/test-10                                               61          18573318 ns/op        1806.57 MB/s       40602 B/op        153 allocs/op
BenchmarkThroughputServerUnlimited/test-10                                            34          44981690 ns/op         745.95 MB/s     9715981 B/op     143705 allocs/op
BenchmarkThroughputServerLimited/test-10                                              45         197794024 ns/op         169.64 MB/s     7647449 B/op     134219 allocs/op
BenchmarkThroughputResponseServerSingle/test-10                                       63          18547683 ns/op        1809.06 MB/s        4874 B/op          3 allocs/op
BenchmarkThroughputResponseServerSlowSingle/test-10                                    1        5626165875 ns/op           5.96 MB/s    37918056 B/op     261060 allocs/op
BenchmarkThroughputResponseServerSlowUnlimited/test-10                                31          41335648 ns/op         811.74 MB/s     7577242 B/op     133041 allocs/op
BenchmarkThroughputResponseServerSlowLimited/test-10                                  15          72453039 ns/op         463.11 MB/s     7289918 B/op     131123 allocs/op
BenchmarkSyncThroughputPipe/32_Bytes-10                                             8922            134416 ns/op          23.81 MB/s        1856 B/op        204 allocs/op
BenchmarkSyncThroughputPipe/512_Bytes-10                                            8606            134562 ns/op         380.49 MB/s        1856 B/op        204 allocs/op
BenchmarkSyncThroughputPipe/1024_Bytes-10                                           8887            135223 ns/op         757.27 MB/s        1856 B/op        204 allocs/op
BenchmarkSyncThroughputPipe/2048_Bytes-10                                           8380            136230 ns/op        1503.33 MB/s        1856 B/op        204 allocs/op
BenchmarkSyncThroughputPipe/4096_Bytes-10                                           8486            141589 ns/op        2892.87 MB/s        1857 B/op        204 allocs/op
BenchmarkSyncThroughputNetwork/32_Bytes-10                                          2281            545237 ns/op           5.87 MB/s        1856 B/op        204 allocs/op
BenchmarkSyncThroughputNetwork/512_Bytes-10                                         1987            585061 ns/op          87.51 MB/s        1857 B/op        204 allocs/op
BenchmarkSyncThroughputNetwork/1024_Bytes-10                                        1884            587007 ns/op         174.44 MB/s        1861 B/op        204 allocs/op
BenchmarkSyncThroughputNetwork/2048_Bytes-10                                        1881            616795 ns/op         332.04 MB/s        1861 B/op        204 allocs/op
BenchmarkSyncThroughputNetwork/4096_Bytes-10                                        1836            683971 ns/op         598.86 MB/s        1869 B/op        204 allocs/op
BenchmarkAsyncThroughputLarge/1MB-10                                                 100          11776796 ns/op        8903.75 MB/s       87537 B/op          4 allocs/op
BenchmarkAsyncThroughputLarge/2MB-10                                                  51          22894498 ns/op        9160.07 MB/s       42800 B/op          4 allocs/op
BenchmarkAsyncThroughputLarge/4MB-10                                                  18          63026472 ns/op        6654.83 MB/s      237353 B/op          6 allocs/op
BenchmarkAsyncThroughputLarge/8MB-10                                                   8         128737125 ns/op        6516.08 MB/s     2102436 B/op          8 allocs/op
BenchmarkAsyncThroughputLarge/16MB-10                                                  4         300899135 ns/op        5575.69 MB/s     4200546 B/op         13 allocs/op
BenchmarkSyncThroughputLarge/1MB-10                                                   75          14630519 ns/op        7167.05 MB/s      281395 B/op        205 allocs/op
BenchmarkSyncThroughputLarge/2MB-10                                                   39          31266662 ns/op        6707.31 MB/s     1359684 B/op        208 allocs/op
BenchmarkSyncThroughputLarge/4MB-10                                                   18          69075403 ns/op        6072.07 MB/s     3520140 B/op        210 allocs/op
BenchmarkSyncThroughputLarge/8MB-10                                                    7         146854476 ns/op        5712.19 MB/s    11917470 B/op        216 allocs/op
BenchmarkSyncThroughputLarge/16MB-10                                                   4         300446177 ns/op        5584.10 MB/s    51320190 B/op        227 allocs/op
BenchmarkTCPThroughput/32_Bytes-10                                                 21175             56504 ns/op          56.63 MB/s         304 B/op          4 allocs/op
BenchmarkTCPThroughput/512_Bytes-10                                                12028             99545 ns/op         514.34 MB/s         304 B/op          4 allocs/op
BenchmarkTCPThroughput/1024_Bytes-10                                                7902            153171 ns/op         668.53 MB/s         304 B/op          4 allocs/op
BenchmarkTCPThroughput/2048_Bytes-10                                                4551            266661 ns/op         768.02 MB/s         304 B/op          4 allocs/op
BenchmarkTCPThroughput/4096_Bytes-10                                                2391            503068 ns/op         814.20 MB/s         304 B/op          4 allocs/op
BenchmarkTCPThroughput/1MB-10                                                         70          14571473 ns/op        7196.09 MB/s         304 B/op          4 allocs/op
BenchmarkTCPThroughput/2MB-10                                                         38          28974152 ns/op        7238.01 MB/s         304 B/op          4 allocs/op
BenchmarkTCPThroughput/4MB-10                                                         21          64769454 ns/op        6475.74 MB/s         304 B/op          4 allocs/op
BenchmarkTCPThroughput/8MB-10                                                          8         133104208 ns/op        6302.29 MB/s         304 B/op          4 allocs/op
BenchmarkTCPThroughput/16MB-10                                                         4         292046646 ns/op        5744.70 MB/s         304 B/op          4 allocs/op
PASS
ok      github.com/loopholelabs/frisbee-go      150.153s
?       github.com/loopholelabs/frisbee-go/internal/dialer      [no test files]
goos: darwin
goarch: arm64
pkg: github.com/loopholelabs/frisbee-go/pkg/metadata
BenchmarkEncode-10              100961637               11.67 ns/op
BenchmarkDecode-10              340956633                3.577 ns/op
BenchmarkEncodeDecode-10        77530648                15.12 ns/op
PASS
ok      github.com/loopholelabs/frisbee-go/pkg/metadata 4.725s
PASS
ok      github.com/loopholelabs/frisbee-go/pkg/packet   0.096s
```

@ShivanshVij

### CODE REVIEW

**Comment by ShivanshVij** [comment]
@asalvi0 Please make sure you sign the DCO: https://github.com/loopholelabs/frisbee-go/pull/168/checks?check_run_id=19802889593

**Comment by asalvi0** [comment]
I think this PR is ready for review/merge. Once the new version is published, I'll update [this](https://github.com/loopholelabs/frpc-go/pull/39) one

**Comment by asalvi0** [comment]
seems like `test-race` is timing out in the CI pipeline, all tests are passing locally.

**Review by ShivanshVij — APPROVED** [review]
These changes good

**Pull request merged**
